version: '3.8'
services:
 
  db:
    image: mysql:8.0.22
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "prisma123"      
    volumes:      
      - storage:/var/lib/mysql
    ports:
      - "3306:3306"
      - "33060:33060"

  webadmin:
    image: adminer
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=prisma@fakemail.fake
      - PGADMIN_DEFAULT_PASSWORD=prisma 
    ports:
      - '9999:8080'    
volumes:
  storage:
