version: '3.8'
services:
  # In Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@postgres/
  # Outside Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@localhost:5432/

  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  webadmin:
    image: dpage/pgadmin4:4.29
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=prisma@fakemail.fake
      - PGADMIN_DEFAULT_PASSWORD=prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '9999:80'    
volumes:
  postgres:
