@serverUrl = http://0.0.0.0:3000
@testToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbklkIjo2fQ.mWjBzZnjS-gJ9tGS9BgmohxeiuhXKNV9_6S-5fqzaMY

#### register demo
POST {{serverUrl}}/login
Content-Type: application/json

{
    "email": "testuser@fakemail.fake"
}


#### authenticate
POST {{serverUrl}}/authenticate
Content-Type: application/json

{
    "email": "testuser@fakemail.fake",
    "emailToken": "84557910"
}

### get coureses
GET {{serverUrl}}/courses
Authorization: Bearer {{testToken}}


### get users
GET {{serverUrl}}/users
Authorization: Bearer {{testToken}}